[package]
name = "vision-ssl-protobuf"
version = "0.0.1"
edition = "2021"


[dependencies]
protobuf = "3"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
protobuf-codegen-pure = "2.14"