// This file is generated by rust-protobuf 2.28.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `messages_robocup_ssl_wrapper_tracked.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_28_0;

#[derive(PartialEq,Clone,Default)]
pub struct TrackerWrapperPacket {
    // message fields
    uuid: ::protobuf::SingularField<::std::string::String>,
    source_name: ::protobuf::SingularField<::std::string::String>,
    pub tracked_frame: ::protobuf::SingularPtrField<super::messages_robocup_ssl_detection_tracked::TrackedFrame>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TrackerWrapperPacket {
    fn default() -> &'a TrackerWrapperPacket {
        <TrackerWrapperPacket as ::protobuf::Message>::default_instance()
    }
}

impl TrackerWrapperPacket {
    pub fn new() -> TrackerWrapperPacket {
        ::std::default::Default::default()
    }

    // required string uuid = 1;


    pub fn get_uuid(&self) -> &str {
        match self.uuid.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_uuid(&mut self) {
        self.uuid.clear();
    }

    pub fn has_uuid(&self) -> bool {
        self.uuid.is_some()
    }

    // Param is passed by value, moved
    pub fn set_uuid(&mut self, v: ::std::string::String) {
        self.uuid = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_uuid(&mut self) -> &mut ::std::string::String {
        if self.uuid.is_none() {
            self.uuid.set_default();
        }
        self.uuid.as_mut().unwrap()
    }

    // Take field
    pub fn take_uuid(&mut self) -> ::std::string::String {
        self.uuid.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string source_name = 2;


    pub fn get_source_name(&self) -> &str {
        match self.source_name.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_source_name(&mut self) {
        self.source_name.clear();
    }

    pub fn has_source_name(&self) -> bool {
        self.source_name.is_some()
    }

    // Param is passed by value, moved
    pub fn set_source_name(&mut self, v: ::std::string::String) {
        self.source_name = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_source_name(&mut self) -> &mut ::std::string::String {
        if self.source_name.is_none() {
            self.source_name.set_default();
        }
        self.source_name.as_mut().unwrap()
    }

    // Take field
    pub fn take_source_name(&mut self) -> ::std::string::String {
        self.source_name.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional .TrackedFrame tracked_frame = 3;


    pub fn get_tracked_frame(&self) -> &super::messages_robocup_ssl_detection_tracked::TrackedFrame {
        self.tracked_frame.as_ref().unwrap_or_else(|| <super::messages_robocup_ssl_detection_tracked::TrackedFrame as ::protobuf::Message>::default_instance())
    }
    pub fn clear_tracked_frame(&mut self) {
        self.tracked_frame.clear();
    }

    pub fn has_tracked_frame(&self) -> bool {
        self.tracked_frame.is_some()
    }

    // Param is passed by value, moved
    pub fn set_tracked_frame(&mut self, v: super::messages_robocup_ssl_detection_tracked::TrackedFrame) {
        self.tracked_frame = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_tracked_frame(&mut self) -> &mut super::messages_robocup_ssl_detection_tracked::TrackedFrame {
        if self.tracked_frame.is_none() {
            self.tracked_frame.set_default();
        }
        self.tracked_frame.as_mut().unwrap()
    }

    // Take field
    pub fn take_tracked_frame(&mut self) -> super::messages_robocup_ssl_detection_tracked::TrackedFrame {
        self.tracked_frame.take().unwrap_or_else(|| super::messages_robocup_ssl_detection_tracked::TrackedFrame::new())
    }
}

impl ::protobuf::Message for TrackerWrapperPacket {
    fn is_initialized(&self) -> bool {
        if self.uuid.is_none() {
            return false;
        }
        for v in &self.tracked_frame {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.uuid)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.source_name)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.tracked_frame)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.uuid.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(ref v) = self.source_name.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(ref v) = self.tracked_frame.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.uuid.as_ref() {
            os.write_string(1, &v)?;
        }
        if let Some(ref v) = self.source_name.as_ref() {
            os.write_string(2, &v)?;
        }
        if let Some(ref v) = self.tracked_frame.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TrackerWrapperPacket {
        TrackerWrapperPacket::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "uuid",
                |m: &TrackerWrapperPacket| { &m.uuid },
                |m: &mut TrackerWrapperPacket| { &mut m.uuid },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "source_name",
                |m: &TrackerWrapperPacket| { &m.source_name },
                |m: &mut TrackerWrapperPacket| { &mut m.source_name },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::messages_robocup_ssl_detection_tracked::TrackedFrame>>(
                "tracked_frame",
                |m: &TrackerWrapperPacket| { &m.tracked_frame },
                |m: &mut TrackerWrapperPacket| { &mut m.tracked_frame },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TrackerWrapperPacket>(
                "TrackerWrapperPacket",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TrackerWrapperPacket {
        static instance: ::protobuf::rt::LazyV2<TrackerWrapperPacket> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TrackerWrapperPacket::new)
    }
}

impl ::protobuf::Clear for TrackerWrapperPacket {
    fn clear(&mut self) {
        self.uuid.clear();
        self.source_name.clear();
        self.tracked_frame.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TrackerWrapperPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TrackerWrapperPacket {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n*messages_robocup_ssl_wrapper_tracked.proto\x1a,messages_robocup_ssl_d\
    etection_tracked.proto\"\x87\x01\n\x14TrackerWrapperPacket\x12\x14\n\x04\
    uuid\x18\x01\x20\x02(\tR\x04uuidB\0\x12!\n\x0bsource_name\x18\x02\x20\
    \x01(\tR\nsourceNameB\0\x124\n\rtracked_frame\x18\x03\x20\x01(\x0b2\r.Tr\
    ackedFrameR\x0ctrackedFrameB\0:\0B\0b\x06proto2\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
