// This file is generated by rust-protobuf 2.28.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `messages_robocup_ssl_wrapper_legacy.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_28_0;

#[derive(PartialEq,Clone,Default)]
pub struct SSL_WrapperPacket {
    // message fields
    pub detection: ::protobuf::SingularPtrField<super::messages_robocup_ssl_detection::SSL_DetectionFrame>,
    pub geometry: ::protobuf::SingularPtrField<super::messages_robocup_ssl_geometry_legacy::SSL_GeometryData>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SSL_WrapperPacket {
    fn default() -> &'a SSL_WrapperPacket {
        <SSL_WrapperPacket as ::protobuf::Message>::default_instance()
    }
}

impl SSL_WrapperPacket {
    pub fn new() -> SSL_WrapperPacket {
        ::std::default::Default::default()
    }

    // optional .SSL_DetectionFrame detection = 1;


    pub fn get_detection(&self) -> &super::messages_robocup_ssl_detection::SSL_DetectionFrame {
        self.detection.as_ref().unwrap_or_else(|| <super::messages_robocup_ssl_detection::SSL_DetectionFrame as ::protobuf::Message>::default_instance())
    }
    pub fn clear_detection(&mut self) {
        self.detection.clear();
    }

    pub fn has_detection(&self) -> bool {
        self.detection.is_some()
    }

    // Param is passed by value, moved
    pub fn set_detection(&mut self, v: super::messages_robocup_ssl_detection::SSL_DetectionFrame) {
        self.detection = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_detection(&mut self) -> &mut super::messages_robocup_ssl_detection::SSL_DetectionFrame {
        if self.detection.is_none() {
            self.detection.set_default();
        }
        self.detection.as_mut().unwrap()
    }

    // Take field
    pub fn take_detection(&mut self) -> super::messages_robocup_ssl_detection::SSL_DetectionFrame {
        self.detection.take().unwrap_or_else(|| super::messages_robocup_ssl_detection::SSL_DetectionFrame::new())
    }

    // optional .RoboCup2014Legacy.Geometry.SSL_GeometryData geometry = 2;


    pub fn get_geometry(&self) -> &super::messages_robocup_ssl_geometry_legacy::SSL_GeometryData {
        self.geometry.as_ref().unwrap_or_else(|| <super::messages_robocup_ssl_geometry_legacy::SSL_GeometryData as ::protobuf::Message>::default_instance())
    }
    pub fn clear_geometry(&mut self) {
        self.geometry.clear();
    }

    pub fn has_geometry(&self) -> bool {
        self.geometry.is_some()
    }

    // Param is passed by value, moved
    pub fn set_geometry(&mut self, v: super::messages_robocup_ssl_geometry_legacy::SSL_GeometryData) {
        self.geometry = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_geometry(&mut self) -> &mut super::messages_robocup_ssl_geometry_legacy::SSL_GeometryData {
        if self.geometry.is_none() {
            self.geometry.set_default();
        }
        self.geometry.as_mut().unwrap()
    }

    // Take field
    pub fn take_geometry(&mut self) -> super::messages_robocup_ssl_geometry_legacy::SSL_GeometryData {
        self.geometry.take().unwrap_or_else(|| super::messages_robocup_ssl_geometry_legacy::SSL_GeometryData::new())
    }
}

impl ::protobuf::Message for SSL_WrapperPacket {
    fn is_initialized(&self) -> bool {
        for v in &self.detection {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.geometry {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.detection)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.geometry)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.detection.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.geometry.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.detection.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.geometry.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SSL_WrapperPacket {
        SSL_WrapperPacket::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::messages_robocup_ssl_detection::SSL_DetectionFrame>>(
                "detection",
                |m: &SSL_WrapperPacket| { &m.detection },
                |m: &mut SSL_WrapperPacket| { &mut m.detection },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::messages_robocup_ssl_geometry_legacy::SSL_GeometryData>>(
                "geometry",
                |m: &SSL_WrapperPacket| { &m.geometry },
                |m: &mut SSL_WrapperPacket| { &mut m.geometry },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SSL_WrapperPacket>(
                "SSL_WrapperPacket",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SSL_WrapperPacket {
        static instance: ::protobuf::rt::LazyV2<SSL_WrapperPacket> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SSL_WrapperPacket::new)
    }
}

impl ::protobuf::Clear for SSL_WrapperPacket {
    fn clear(&mut self) {
        self.detection.clear();
        self.geometry.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SSL_WrapperPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SSL_WrapperPacket {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n)messages_robocup_ssl_wrapper_legacy.proto\x12\x19RoboCup2014Legacy.Wr\
    apper\x1a$messages_robocup_ssl_detection.proto\x1a*messages_robocup_ssl_\
    geometry_legacy.proto\"\x96\x01\n\x11SSL_WrapperPacket\x123\n\tdetection\
    \x18\x01\x20\x01(\x0b2\x13.SSL_DetectionFrameR\tdetectionB\0\x12J\n\x08g\
    eometry\x18\x02\x20\x01(\x0b2,.RoboCup2014Legacy.Geometry.SSL_GeometryDa\
    taR\x08geometryB\0:\0B\0b\x06proto2\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
